"""Config for the fpmul_f16 ABC/Opus-5 rerun.

Fixed facts (paths, benchmark, verification setup) live here. SCALE lives in
profiles/<name>.yaml — "full" (the submission-mirroring run) or "reduced" (a
cheap end-to-end rehearsal). The profile is chosen via run_all.py --profile,
which exports RTLSCOUT_RERUN_PROFILE for every stage/subprocess; standalone
stage invocations read the same variable (default: full).

Each profile owns a disjoint output namespace derived from its `tag` (runs/,
pareto_fronts/, state/, figures/, verify_work/, manifest, report), so a
reduced rehearsal can never contaminate the full run.

Deviations from metadocuments/reruns/inputs/HANDOVER_fpmul_rerun.md are
marked with # DEVIATION.
"""
import os
from pathlib import Path

import yaml

REPO = Path("/workspaces/rtl_scout")
VENV_PYTHON = Path.home() / "pyenv_eda" / "bin" / "python"

ARTIFACTS = REPO / "artifacts" / "fpmul_run"

# ---------------------------------------------------------------- profile
PROFILE = os.environ.get("RTLSCOUT_RERUN_PROFILE", "full")
_PROFILE_FILE = ARTIFACTS / "profiles" / f"{PROFILE}.yaml"
if not _PROFILE_FILE.exists():
    raise RuntimeError(f"unknown rerun profile '{PROFILE}' ({_PROFILE_FILE} missing)")
_P = yaml.safe_load(_PROFILE_FILE.read_text())
PROFILE_FILE = _PROFILE_FILE             # snapshotted into DATA by run_all

TAG = _P["tag"]
MODEL = _P["model"]           # DEVIATION (user request): Opus 5 everywhere; the
                              # handover mirrored the older paper (Sonnet for
                              # Phase-1 area). Superseded by the 2026-06-19
                              # submission: one model, symmetric campaigns.

# Every generated byte of a run lives under this one folder (user decision
# 2026-07-29): archive data/<run>/ and you have the complete experiment.
# Only the benchmark mutations (golden, tb, vectors) stay global by design.
# Rehearsal data from before this layout is grandfathered in the old
# locations (runs/fpmul_o5r*, pareto_fronts/fpmul_o5r*, artifacts-level
# state/figures/logs/manifest/REPORT files).
#
# Run naming (user decision 2026-07-29): data/<tag>_<datetime> so repeated
# runs never overwrite. The timestamp is minted ONCE per run (run_all.py
# --new-run) and pinned via the .latest_<profile> pointer — plain
# invocations resume the pointed run, preserving all marker/resume
# semantics. RTLSCOUT_RERUN_RUN selects any specific run (e.g. to
# regenerate an old run's report).
_DATA_ROOT = ARTIFACTS / "data"
_POINTER = _DATA_ROOT / f".latest_{PROFILE}"
RUN_NAME = os.environ.get("RTLSCOUT_RERUN_RUN")
if not RUN_NAME and os.environ.get("RTLSCOUT_RERUN_NEW") == "1":
    import datetime as _dt
    RUN_NAME = f"{TAG}_{_dt.datetime.now():%Y%m%d_%H%M%S}"
    _DATA_ROOT.mkdir(parents=True, exist_ok=True)
    _POINTER.write_text(RUN_NAME + "\n")
    # Pin for child processes: they must join THIS run, never mint another.
    os.environ["RTLSCOUT_RERUN_NEW"] = "0"
    os.environ["RTLSCOUT_RERUN_RUN"] = RUN_NAME
if not RUN_NAME and _POINTER.exists():
    RUN_NAME = _POINTER.read_text().strip()
if not RUN_NAME:
    RUN_NAME = TAG      # ad-hoc imports before any --new-run: unstamped legacy dir
DATA = _DATA_ROOT / RUN_NAME
LOGS = DATA / "logs"
STATE = DATA / "state"                 # stage .done markers + small JSON results
FIGURES = DATA / "figures"
VERIFY_WORK = DATA / "verify_work"
MANIFEST = DATA / "manifest.json"
REPORT_MD = DATA / "REPORT.md"

# ---------------------------------------------------------------- benchmark
BENCHMARK = REPO / "benchmarks" / "fpmul_f16"
CONTEXT = BENCHMARK / "context"
GOLDEN = CONTEXT / "design.v"        # generated by stage 0 from starting_point.py
STARTING_POINT = CONTEXT / "starting_point.py"
TOP_MODULE = "fp_mul_e5f10"

ASSETS = REPO / "metadocuments" / "reruns" / "assets"
OLD_GOLDEN = ASSETS / "old_results" / "fpmul_initial_design" / "design_000" / "design.v"
# Known-buggy old design: positive control for the verification harness.
BUGGY_CONTROL = ASSETS / "old_results" / "pareto_fpmul" / "design_005" / "design.v"

# The 3 regression inputs (a, b, correct y) from the handover; buggy designs
# return y-1 on all three.
REGRESSION_VECTORS = [
    (0x0003, 0x6801, 0x0E02),
    (0x8003, 0x6479, 0x8AB6),
    (0x7521, 0x0003, 0x1BB2),
]

# Directed cross-check stimuli appended to vectors.dat (~8k, bringing the file
# to ~10k). Benchmark mutations are GLOBAL — deliberately not profile-scoped.
DIRECTED_CLASS_COUNTS = {
    "subnormal_x_normal": 1500,
    "normal_x_subnormal": 1500,
    "subnormal_x_subnormal": 500,
    "boundary_product": 2000,        # products near the subnormal/normal boundary
    "mantissa_edge": 1000,           # mantissa in {0, 1, 0x3FF}
    "specials": 500,                 # zeros, infs, max-finite overflow
    "random_normal": 1000,
}
DIRECTED_VECTOR_SEED = 20260727      # reproducible numpy RNG seed
VECTOR_MARKER = "# directed subnormal vectors (fpmul_run)"

# In-loop testbench (user decision 2026-07-27): golden-referenced directed
# enumeration in tb.sv itself (~18.9M vectors, no stimuli file) — full
# exhaustive per eval is infeasible (measured: 8.4M vec/s RTL => 8.5 min,
# 0.6M vec/s netlist => ~2 h for 2^32). The old file-driven tb is parked at
# tb_vectors.sv (+ vectors.dat) for cross-checking.
TB_MARKER = "// exhaustive-directed tb (fpmul_run)"
TB_BACKUP = BENCHMARK / "tb_vectors.sv"

# ---------------------------------------------------------------- outputs
# Fresh, explicitly named dirs only — never reuse or overwrite existing
# content (handover decision 3); all under DATA per the layout above.
RUNS_SMOKE = DATA / "runs" / "smoke"

# FRONTS doubles as the sweep's --references-dir: the sweep discovers every
# "pareto_*" folder inside it, so ONLY sweep inputs carry that prefix.
FRONTS = DATA / "fronts"
FRONT_ABC = FRONTS / "pareto_fpmul_abc"          # Phases 1+2 combined front
FRONT_NO_ABC = FRONTS / "pareto_fpmul_no_abc"    # Phase-1-only ablation front
FRONT_SWEEP_DEDUP = FRONTS / "sweep_dedup"       # post-sweep front (feeds Phase 4)
FRONT_SWEEP_FULL = FRONTS / "sweep_full"
FRONT_DEEPSYN_REFINE = FRONTS / "deepsyn_refine"
FRONT_FINAL = FRONTS / "final"                   # Pareto(Phase 4 u Phase-3 seeds)
FRONT_INITIAL_DEEPSYN = FRONTS / "initial_deepsyn"   # equal-compute baseline
FRONT_INITIAL_DEEPSYN_2X = FRONTS / "initial_deepsyn_2x"  # optional 2x-effort baseline

# The sweep's outputs (results JSON, quick-look PNGs, worker_* synthesis
# dirs) are all cwd-relative — stage 3 runs it with cwd=SWEEP_DIR, which
# relocates everything here without touching deps/tech_eval.
SWEEP_DIR = DATA / "sweep"
SWEEP_RESULTS = SWEEP_DIR / "results" / "ppa" / "FpMul_e5f10_results.json"

# ---------------------------------------------------------------- campaigns
MAX_STEPS = _P["agent"]["max_steps"]
ELITE_SIZE = _P["agent"]["elite_size"]
AGENT_TARGET_DELAY = _P["agent"]["target_delay"]
LANGUAGE = "spirehdl"
# Phase 2 = seeded search + @abc_optimized. Setting this false keeps the
# seeded search and withholds the decorator, isolating what the decorator
# itself buys (the existing FRONT_NO_ABC is phase-1-only, a different
# ablation). Defaults true so every pre-existing profile is unaffected.
P2_ABC_OPTIMIZE = bool(_P.get("p2_abc_optimize", True))
# Front-construction knobs, for arms that must match an EARLIER run's handoff
# sizes rather than the current pipeline's defaults. All default to today's
# behaviour so existing profiles are unaffected.
_F = _P.get("fronts") or {}
# Pool the area_delay_product campaigns into the phase-1/2 fronts. The glm52
# paper run predates ADP pooling and used area+delay only; an arm compared
# against it must do the same or it draws from a strictly larger pool.
FRONT_INCLUDE_ADP = bool(_F.get("include_adp", True))
# Cap on phase-1/2 front size (the p2->p3 handoff). None = no cap.
FRONT_MAX_POINTS = _F.get("max_points")


def _campaigns(entries):
    rows = []
    for e in entries:
        seed = DATA / "runs" / e["seed_from"] if e.get("seed_from") else None
        rows.append((e["name"], DATA / "runs" / e["name"],
                     e["metric"], e["runs"], e["concurrent"], e["fresh_first"], seed,
                     e.get("fresh_base"), e.get("fresh_min")))
    return rows


# (name, runs-root, cost metric, total runs, max concurrent, fresh-first,
#  seed-from, fresh-base, fresh-min); fresh-base/min None = repo defaults.
CAMPAIGNS_P1 = _campaigns(_P["campaigns_p1"])
CAMPAIGNS_P2 = _campaigns(_P["campaigns_p2"])
def _runs_root(campaigns, metric):
    """Runs-root of the campaign optimizing *metric*, or None if absent.

    Looked up by metric rather than by position so a profile can add, drop or
    reorder campaigns (e.g. a third area_delay_product branch) without the
    named constants below silently pointing at the wrong one.
    """
    for row in campaigns:
        if row[2] == metric:
            return row[1]
    return None


RUNS_P1_AREA = _runs_root(CAMPAIGNS_P1, "area")
RUNS_P1_DELAY = _runs_root(CAMPAIGNS_P1, "delay")
RUNS_P1_ADP = _runs_root(CAMPAIGNS_P1, "area_delay_product")
RUNS_P2_AREA = _runs_root(CAMPAIGNS_P2, "area")
RUNS_P2_DELAY = _runs_root(CAMPAIGNS_P2, "delay")
RUNS_P2_ADP = _runs_root(CAMPAIGNS_P2, "area_delay_product")

# ---------------------------------------------------------------- stages 3/4
SWEEP_SINGLE_POINT = bool(_P["sweep"]["single_point"])
# Cap on the post-sweep dedup front (the p3->p4 handoff). None = no cap.
# Stage 4's trajectory count is n_designs x refine_runs, so this also fixes
# phase-4 compute — an uncapped arm gets more of it than the run it is
# compared against.
SWEEP_DEDUP_MAX_POINTS = _P["sweep"].get("dedup_max_points")
DEEPSYN_TIME_BUDGET = _P["deepsyn"]["time_budget"]
DEEPSYN_REFINE_RUNS = _P["deepsyn"]["refine_runs"]
EQUAL_COMPUTE_RUNS = _P["deepsyn"]["equal_compute_runs"]   # None = full 650
# Optional double-effort from-scratch arm (2x per-trajectory time budget,
# same trajectory count): comparison baseline only, NOT method cost.
DEEPSYN_DOUBLE_EFFORT = bool(_P["deepsyn"].get("double_effort", False))
DEEPSYN_WORKERS = _P["deepsyn"]["workers"]
EVAL_TARGET_DELAYS = [float(t) for t in _P["eval"]["target_delays"]]
EVAL_WORKERS = _P["eval"]["workers"]
# Sweep synthesis targets: profile override, else the eval targets — so every
# reported number in the paper sits at the same operating points.
SWEEP_TARGET_DELAYS = ([float(t) for t in _P["sweep"]["target_delays"]]
                       if _P["sweep"].get("target_delays") else EVAL_TARGET_DELAYS)

# ---------------------------------------------------------------- verification
# DEVIATION (user decision 2026-07-27): no post-hoc CEC attempt — exhaustive
# simulation is already complete for this combinational design.
EXHAUSTIVE_SHARDS = 128              # must divide 65536 (shard = range of a)
VERIFY_JOBS = 110                    # concurrent shard processes

SMOKE_MAX_STEPS = 8
