"""Config for the PDPU library-core experiment (fpmul_run-style layout).

Scale lives in profiles/<name>.yaml; every generated byte of a run lives
under data/<tag>_<datetime>/ (--new-run mints and pins the run via
data/.latest_<profile>; plain invocations resume)."""
import os
from pathlib import Path

import yaml

REPO = Path("/workspaces/rtl_scout")
VENV_PYTHON = Path.home() / "pyenv_eda" / "bin" / "python"
ARTIFACTS = REPO / "artifacts" / "pdpu_run"

PROFILE = os.environ.get("RTLSCOUT_PDPU_PROFILE", "reduced")
_PF = ARTIFACTS / "profiles" / f"{PROFILE}.yaml"
if not _PF.exists():
    raise RuntimeError(f"unknown profile '{PROFILE}' ({_PF} missing)")
_P = yaml.safe_load(_PF.read_text())
PROFILE_FILE = _PF

TAG = _P["tag"]
MODEL = _P["model"]

_DATA_ROOT = ARTIFACTS / "data"
_POINTER = _DATA_ROOT / f".latest_{PROFILE}"
RUN_NAME = os.environ.get("RTLSCOUT_PDPU_RUN")
if not RUN_NAME and os.environ.get("RTLSCOUT_PDPU_NEW") == "1":
    import datetime as _dt
    RUN_NAME = f"{TAG}_{_dt.datetime.now():%Y%m%d_%H%M%S}"
    _DATA_ROOT.mkdir(parents=True, exist_ok=True)
    _POINTER.write_text(RUN_NAME + "\n")
    os.environ["RTLSCOUT_PDPU_NEW"] = "0"
    os.environ["RTLSCOUT_PDPU_RUN"] = RUN_NAME
if not RUN_NAME and _POINTER.exists():
    RUN_NAME = _POINTER.read_text().strip()
if not RUN_NAME:
    RUN_NAME = TAG
DATA = _DATA_ROOT / RUN_NAME
LOGS = DATA / "logs"
STATE = DATA / "state"
MANIFEST = DATA / "manifest.json"
REPORT_MD = DATA / "REPORT.md"

BENCHMARKS = _P["benchmarks"]            # {language: benchmark_name}
BENCH_ROOTS = [str(REPO / "benchmarks"), str(REPO / "internal" / "benchmarks")]

FRONTS = DATA / "fronts"

# Design interface for the deepsyn AIG flow. Widths only — the emitted
# wrapper's PI/PO order comes from yosys `write_aiger -map`.
TOP_MODULE = _P.get("top_module", "pdpu_top")
DEEPSYN_INPUTS = _P["ports"]["inputs"]
DEEPSYN_OUTPUTS = _P["ports"]["outputs"]

MAX_STEPS = _P["agent"]["max_steps"]
ELITE_SIZE = _P["agent"]["elite_size"]
TARGET_DELAY = float(_P["agent"]["target_delay"])

# Per-phase agent campaigns, one per objective (fpmul shape). Each entry:
# {name, metric, runs, concurrent, seed_from?}.
CAMPAIGNS = {1: _P["campaigns_p1"], 2: _P["campaigns_p2"]}

# Phase-4 seed-set size: truncates (pinning both extremes) or pads with
# best-scoring non-Pareto designs. Feeds extract_pareto.py -n.
FRONT_N_POINTS = _P.get("front", {}).get("n_points")

DEEPSYN_T = int(_P["deepsyn"]["time_budget"])
DEEPSYN_REFINE_RUNS = int(_P["deepsyn"]["refine_runs"])
DEEPSYN_WORKERS = int(_P["deepsyn"]["workers"])
# Optional 2x-budget from-scratch arm (same trajectory count, 2x time each) —
# the fpmul suite's "double effort" comparison baseline.
DEEPSYN_DOUBLE_EFFORT = bool(_P["deepsyn"].get("double_effort", False))

# Reporting operating points: every number in the table is measured here, so
# rows stay comparable no matter what target the agent chose for itself.
EVAL_TARGET_DELAYS = [float(t) for t in _P["eval"]["target_delays"]]
EVAL_WORKERS = int(_P["eval"]["workers"])

# RTLRewriter recipe (spire-only flags; verilog runs carry none): phase 1 is
# decorator-free structural exploration, phase 2 polishes the P1 elite with
# them — see experiments/rtl_rewriter_multirun.py:_phase_flags for the why.
PHASE_FLAGS = {
    "spirehdl": {1: [],
                 2: ["--arith-autoconfig", "--abc-optimize"]},
    "verilog": {1: [], 2: []},
}

# OpenRouter pricing (USD / 1M tokens)
PRICING = {"input": 0.6916, "output": 2.1736, "cache_write": 0.0,
           "cache_read": 0.12844}
