"""Stage 3 — arithmetic architecture sweep (paper Phase 3).

Patchability gate first: every front design must be auto-patchable by the
sweep's strict AST matcher, otherwise it would silently sweep 183 identical
configurations. On gate failure we STOP — loosening the matcher toward the
fpadd style is a deliberate code change to deps/tech_eval, not something to
do silently (handover Stage 3).
"""
import datetime
import json
import os
import subprocess
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import common
import rerun_config as cfg
import stagev_verify

TECH_EVAL = cfg.REPO / "deps" / "tech_eval"
TE_ENV = {"PYTHONPATH": str(TECH_EVAL / "src") + ":" + str(cfg.REPO),
          # The sweep's plot epilogue must never touch the session's X display
          # (a dead DISPLAY killed a finished sweep with an XIO fatal).
          "MPLBACKEND": "Agg"}


_INIT_REFERENCE_PY = '''\
"""Unmodified starting architecture for the sweep — the paper's
"Phase 3 only (init + arch sweep)" ablation (old results case
pareto_front_init/design_000). FpMulSN takes mult_cfg/adder_cfg natively, so
no AST patching is involved; the explicit Component base satisfies the
loader's script-shape check (it only imports scripts whose class visibly
inherits Component).

Generated by artifacts/fpmul_run/stages/stage3_sweep.py.
"""
from spire import Component
from spire.arithmetic.floating_point.float_mult_sn import FpMulSN


class FpMulInit(FpMulSN, Component):
    pass
'''


def prepare_init_reference() -> Path:
    """Create FRONTS/pareto_front_init/design_000/design.py: the sweep entry
    for the starting design, mirroring the old pipeline's ablation case."""
    d = cfg.FRONTS / "pareto_front_init" / "design_000"
    d.mkdir(parents=True, exist_ok=True)
    script = d / "design.py"
    if not script.exists() or script.read_text() != _INIT_REFERENCE_PY:
        script.write_text(_INIT_REFERENCE_PY)
    common.record("stage3", d, "Phase-3-only ablation entry (starting design, "
                  "swept natively via FpMulSN)")
    return script


def _sweep_scripts(front: Path) -> list:
    """EXACTLY the sweep's own selection (_discover_pareto_designs): first
    *.py per design dir, excluding *_component.py. The gate must validate the
    file the sweep will actually load — using pareto_front.json's design file
    here once let a convertible lib pass while the sweep loaded another."""
    out = []
    for d in sorted(x for x in front.glob("design_*") if x.is_dir()):
        scripts = [s for s in sorted(d.glob("*.py"))
                   if not s.name.endswith("_component.py")]
        if scripts:
            out.append(scripts[0])
    return out


def patchability_gate() -> None:
    designs = [prepare_init_reference()]
    for front in (cfg.FRONT_ABC, cfg.FRONT_NO_ABC):
        designs += _sweep_scripts(front)
    if not designs:
        raise RuntimeError("patchability gate: no design scripts found in fronts")
    proc = subprocess.run(
        common.py(Path(__file__).parent / "patch_gate.py", *designs),
        capture_output=True, text=True, cwd=cfg.REPO,
        env={**__import__("os").environ, **TE_ENV})
    if proc.returncode != 0:
        raise RuntimeError(f"patch_gate.py crashed:\n{proc.stderr}")
    results = [json.loads(l[len("GATE_RESULT "):]) for l in proc.stdout.splitlines()
               if l.startswith("GATE_RESULT ")]
    common.save_state("patchability", {"results": results})
    failures = [r for r in results if not r["ok"]]
    common.log(f"patchability gate: {len(results) - len(failures)}/{len(results)} ok")
    if failures:
        for f in failures:
            common.log(f"  UNPATCHABLE {f['path']}: {f['error']}")
        fail_dirs = "\n".join(f"    mv {Path(f['path']).parent} "
                              f"{Path(f['path']).parent.parent}/unswept_"
                              f"{Path(f['path']).parent.name}"
                              for f in failures)
        raise RuntimeError(
            f"{len(failures)} design(s) not auto-patchable by the sweep "
            f"converter (details: {cfg.STATE / 'patchability.json'}).\n"
            f"OPERATOR ACTION — for each failing design, either:\n"
            f"  (a) set it aside so the sweep skips it (it STAYS on the "
            f"reported, Stage-V-verified front; only Phase 3 skips it):\n"
            f"{fail_dirs}\n"
            f"  (b) or extend the converter/matcher in "
            f"deps/tech_eval/src/tech_eval/ppa_extract/sweeps/fpmul/"
            f"script_to_component.py (fpadd-style loosening, handover Stage 3) "
            f"and record the change in STATUS.md.\n"
            f"Then RERUN the same command (run_all.py --profile {cfg.PROFILE}) "
            f"— completed stages and a finished sweep are skipped via markers, "
            f"so it resumes right here at stage 3.")


def run_sweep() -> None:
    if common.stage_done("sweep"):
        common.log("sweep already done — skipping")
        return
    if cfg.SWEEP_RESULTS.exists():
        ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        backup = cfg.SWEEP_RESULTS.with_suffix(f".pre_{cfg.TAG}_{ts}.json")
        cfg.SWEEP_RESULTS.rename(backup)
        common.log(f"existing sweep results moved aside: {backup}")
    cmd = [cfg.VENV_PYTHON, "-m", "tech_eval.ppa_extract.sweeps.fpmul.fpmul_sweep_mp",
           "--references-dir", cfg.FRONTS,
           "--target-delays", *[str(t) for t in cfg.SWEEP_TARGET_DELAYS]]
    if cfg.SWEEP_SINGLE_POINT:
        cmd += ["--single-point"]
    # cwd=SWEEP_DIR relocates every cwd-relative sweep output (results JSON,
    # quick-look PNGs, worker_* synthesis dirs) under data/<tag>/sweep/.
    cfg.SWEEP_DIR.mkdir(parents=True, exist_ok=True)
    common.sh(cmd, "stage3_sweep", cwd=cfg.SWEEP_DIR, env_extra=TE_ENV)
    if not cfg.SWEEP_RESULTS.exists():
        raise RuntimeError(f"sweep finished but {cfg.SWEEP_RESULTS} was not written")
    common.record("stage3", cfg.SWEEP_RESULTS, "architecture sweep results (all configs)")
    common.mark_done("sweep")


def _normalize_top_module(front: Path) -> None:
    """The sweep emits netlists as ``module Design (clk, a, b, y)``: rename
    the top to the benchmark's module AND strip the dead clk port. The rename
    serves Stage V / batch_deepsyn / batch_eval (all assume fp_mul_e5f10);
    the clk strip is essential for batch_deepsyn, whose AIG wrapper maps
    primary inputs POSITIONALLY — a leftover clk PI shifts a/b by one bit
    and yields functional garbage (found by the reduced rehearsal)."""
    import re
    for v in sorted(front.glob("design_*/*.v")):
        text = v.read_text()
        mods = set(re.findall(r"\bmodule\s+(\w+)", text))
        if len(mods) == 1 and cfg.TOP_MODULE not in mods:
            text = re.sub(rf"\b{mods.pop()}\b", cfg.TOP_MODULE, text)
        elif cfg.TOP_MODULE not in mods:
            common.log(f"normalize: {v} has modules {mods} — left untouched")
            continue
        n_clk = len(re.findall(r"\bclk\b", text))
        if n_clk == 2:                       # port list entry + input decl
            text = re.sub(r"\(\s*clk\s*,", "(", text, count=1)
            text = re.sub(r"^\s*input\s+clk\s*;\s*\n", "", text, count=1, flags=re.M)
            if re.search(r"\bclk\b", text):
                raise RuntimeError(f"normalize: clk strip left references in {v}")
        elif n_clk != 0:
            raise RuntimeError(f"normalize: {v} references clk {n_clk}x — "
                               f"not the expected dead-port pattern")
        v.write_text(text)


def extract() -> None:
    # cwd=SWEEP_DIR so any cwd-relative worker paths in the results resolve.
    common.ensure_fresh(cfg.FRONT_SWEEP_DEDUP)
    common.sh(common.py(cfg.REPO / "extract_sweep_pareto.py", cfg.SWEEP_RESULTS,
                        "-o", cfg.FRONT_SWEEP_DEDUP, "--separate-dirs"),
              "stage3_extract_dedup", cwd=cfg.SWEEP_DIR)
    _normalize_top_module(cfg.FRONT_SWEEP_DEDUP)
    common.record("stage3", cfg.FRONT_SWEEP_DEDUP, "post-sweep Pareto (dedup, feeds Phase 4)")
    common.ensure_fresh(cfg.FRONT_SWEEP_FULL)
    common.sh(common.py(cfg.REPO / "extract_sweep_pareto.py", cfg.SWEEP_RESULTS,
                        "-o", cfg.FRONT_SWEEP_FULL, "--separate-dirs", "--no-deduplicate"),
              "stage3_extract_full", cwd=cfg.SWEEP_DIR)
    _normalize_top_module(cfg.FRONT_SWEEP_FULL)
    common.record("stage3", cfg.FRONT_SWEEP_FULL, "post-sweep Pareto (no dedup)")


def _drop_sweep_scratch() -> None:
    """Delete the per-config synthesis scratch (sweep/worker_*).

    Safe only HERE: extract() and the Stage-V gate both read design.v out of
    those dirs via the results' worker_path, so the sweep cannot clean up at its
    own source. The 61-config x N-design grid builds a full Verilated model per
    point -- 248 GB had accumulated across six runs before this was added, while
    the results it produces (sweep/results/) are a few MB. Set
    RTLSCOUT_KEEP_SWEEP_SCRATCH=1 to inspect a sweep instead.
    """
    if os.environ.get("RTLSCOUT_KEEP_SWEEP_SCRATCH"):
        common.log("keeping sweep scratch (RTLSCOUT_KEEP_SWEEP_SCRATCH set)")
        return
    workers = sorted(cfg.SWEEP_DIR.glob("worker_*"))
    if not workers:
        return
    freed = sum(f.stat().st_size for w in workers for f in w.rglob("*") if f.is_file())
    for w in workers:
        shutil.rmtree(w, ignore_errors=True)
    common.log(f"removed {len(workers)} sweep worker dirs "
               f"({freed / 2**30:.1f} GiB); sweep/results kept")


def run() -> None:
    patchability_gate()
    run_sweep()
    extract()
    s = stagev_verify.verify_front(cfg.FRONT_SWEEP_DEDUP, "sweep_dedup")
    if s["passed"] == 0:
        raise RuntimeError(
            "stage 3: every post-sweep design failed verification — that is a "
            "pipeline defect (or a broken extraction), not a QoR outcome; see "
            f"{cfg.FRONT_SWEEP_DEDUP / 'verification_results.md'}")
    _drop_sweep_scratch()
    common.mark_done("stage3")


if __name__ == "__main__":
    run()
