"""Config for the RTLRewriter rerun (Opus 4.8, ABC-only phase 2,
post-hoc CEC). Scale lives in profiles/<name>.yaml; every generated byte of a
run lives under data/<tag>_<datetime>/ (fpmul-rerun layout: --new-run mints
and pins the run via data/.latest_<profile>; plain invocations resume)."""
import os
from pathlib import Path

import yaml

REPO = Path("/workspaces/rtl_scout")
VENV_PYTHON = Path.home() / "pyenv_eda" / "bin" / "python"
ARTIFACTS = REPO / "artifacts" / "rtlrewriter_run"

PROFILE = os.environ.get("RTLSCOUT_RRRERUN_PROFILE", "full")
_PF = ARTIFACTS / "profiles" / f"{PROFILE}.yaml"
if not _PF.exists():
    raise RuntimeError(f"unknown profile '{PROFILE}' ({_PF} missing)")
_P = yaml.safe_load(_PF.read_text())
PROFILE_FILE = _PF                       # snapshotted into DATA by run_all

TAG = _P["tag"]
MODEL = _P["model"]

_DATA_ROOT = ARTIFACTS / "data"
_POINTER = _DATA_ROOT / f".latest_{PROFILE}"
RUN_NAME = os.environ.get("RTLSCOUT_RRRERUN_RUN")
if not RUN_NAME and os.environ.get("RTLSCOUT_RRRERUN_NEW") == "1":
    import datetime as _dt
    RUN_NAME = f"{TAG}_{_dt.datetime.now():%Y%m%d_%H%M%S}"
    _DATA_ROOT.mkdir(parents=True, exist_ok=True)
    _POINTER.write_text(RUN_NAME + "\n")
    os.environ["RTLSCOUT_RRRERUN_NEW"] = "0"
    os.environ["RTLSCOUT_RRRERUN_RUN"] = RUN_NAME
if not RUN_NAME and _POINTER.exists():
    RUN_NAME = _POINTER.read_text().strip()
if not RUN_NAME:
    RUN_NAME = TAG
DATA = _DATA_ROOT / RUN_NAME
LOGS = DATA / "logs"
STATE = DATA / "state"
MANIFEST = DATA / "manifest.json"
REPORT_MD = DATA / "REPORT.md"

CASES = _P["cases"] or list(range(1, 15))
REPETITIONS = _P.get("repetitions", 1)   # independent runner invocations
TOTAL_RUNS = _P["total_runs"]            # runs per phase within one repetition
PHASES = _P["phases"]
WORKERS = _P["workers"]
MAX_CONCURRENT = _P["max_concurrent"]
ELITE_SIZE = _P["elite_size"]
CAMPAIGNS = _P["campaigns"]              # {"cells": {...}, "transistors": {...}}

VEC_TARGET = _P["vectors"]["target_total"]
VEC_SEED = _P["vectors"]["seed"]
VEC_MARKER = "# augmented golden-simulated vectors (rtlrewriter_run)"

CEC_ENGINE = REPO / "artifacts" / "rtlrewriter_benchmark_results" / "cec_engine.py"
CEC_SIM_CASES = _P["cec"]["sim_cases"]
CEC_SIM_VECTORS = _P["cec"]["sim_vectors"]
CEC_WORKERS = _P["cec"]["workers"]

BENCH_TREES = {                          # language -> (benchmarks root, golden file)
    "verilog": (REPO / "benchmarks" / "rtl_rewriter", "context/starting_point.v"),
    "spirehdl": (REPO / "benchmarks" / "rtl_rewriter_spirehdl", "context/starting_point.py"),
}

# USD per 1M tokens (official list, 5m-cache-write tier).
PRICING = {"input": 5.0, "output": 25.0, "cache_write": 6.25, "cache_read": 0.50}
